"""Bayes admission pool for the frozen bidirectional NEED protocol.

No learner is fitted here. Contexts are generated by direction, task need and
seed before either paired SEND/HOLD return is observed.
"""

import argparse
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict
import json
import math
from pathlib import Path

import numpy as np

from .algorithm import acquire_to_evidence, post_reading_branch
from .lookahead import LookaheadSpec
from .lookahead_bidirectional import (BidirectionalLookaheadEnv, NeedPacket,
                                      compatible_need)
from .lookahead_policy import LOOKAHEAD_VIEWS
from .physical_audit import AuditChoice, run_continuation
from .lookahead_recipient_a4 import advance_without_message


DIRECTIONS = {
    "scout_to_carrier": {
        "sender": "scout", "receiver": "carrier", "region": 0,
        "scout_start": (12, 27), "carrier_start": (5, 28)},
    "carrier_to_scout": {
        "sender": "carrier", "receiver": "scout", "region": 1,
        "scout_start": (5, 35), "carrier_start": (12, 34)},
}


def choice(agent, region):
    view, target = LOOKAHEAD_VIEWS[region]
    return AuditChoice(agent, "geometry", view, target)


def finish(state, scan):
    choices = () if scan is None else (scan,)
    selected = () if scan is None else (0,)
    result, final = run_continuation(state, choices, selected,
                                     transmit=False, return_environment=True)
    return result, final


def response_branch(snapshot, packet_id, send, receiver_scan, need):
    _, state = post_reading_branch(snapshot, packet_id, send,
                                   continue_mission=False)
    packet = snapshot.innovation_packets[packet_id]
    receiver = "carrier" if packet.source == "scout" else "scout"
    accepted_for_need = compatible_need(
        packet, need, state.step_index * state.config.dt)
    # An unsolicited or late response is charged and delivered by the radio,
    # but the receiver does not incorporate it into this declared request.
    if send and packet_id in state.received[receiver] and not accepted_for_need:
        evidence = state.received[receiver].pop(packet_id)
        state.forget_delivered_evidence(receiver, evidence, snapshot)
    result, final = finish(state, receiver_scan)
    return {"cost": float(result["score_single_world"]),
            "success": bool(result["success"]),
            "radio": float(result["ledger"]["communication"]),
            "sensing": float(result["ledger"]["sensing"]),
            "risk": float(result["material_exposure"]),
            "steps": int(result["steps"]),
            "scan_executed": bool(receiver_scan is not None and
                                  result["target_region_covered"][0]),
            "accepted_for_need": accepted_for_need,
            "support": final.support_metrics()}


def evaluate(seed, direction, world, context, need_age=0):
    setup = DIRECTIONS[direction]
    region = setup["region"]
    surface = [.04, .06]
    traction = [.90, .90]
    surface[region] = .95 if world == "risky" else .04
    traction[region] = .20 if world == "risky" else .90
    spec = LookaheadSpec(seed, surface=tuple(surface), traction=tuple(traction),
                         scout_start=setup["scout_start"],
                         carrier_start=setup["carrier_start"])
    env = BidirectionalLookaheadEnv(spec)
    acquired = acquire_to_evidence(env, choice(setup["sender"], region))
    if acquired is None:
        return {"seed": seed, "direction": direction, "world": world,
                "context": context, "failure": "sender acquisition"}
    base = acquired.env
    packet_id = next(packet_id for packet_id, packet in
                     base.innovation_packets.items()
                     if packet.source == setup["sender"] and
                     packet.region == region)

    if context == "redundant":
        _, base = post_reading_branch(base, packet_id, True,
                                      continue_mission=False)
        base = advance_without_message(
            base, max(1, base.config.communication_delay_steps) + 1)

    if need_age:
        base = advance_without_message(base, need_age)
    requested_region = region if context != "irrelevant" else 1-region
    uncertainty = 0. if context == "redundant" else .25
    relevance = 1. if context == "useful" else 0.
    need = NeedPacket(requested_region, "geometry", uncertainty, relevance,
                      (base.step_index + 80) * base.config.dt,
                      float(base.positions[setup["receiver"]][0]),
                      seed % 65536)
    need_id = base.create_need(setup["receiver"], need)
    _, decision = post_reading_branch(base, need_id, True,
                                      continue_mission=False)
    need_delivered = need_id in decision.received[setup["sender"]]
    packet = decision.innovation_packets[packet_id]
    sender_obs = decision.observations()[setup["sender"]]
    kin = np.asarray(sender_obs["kinematics"], dtype=float)
    sender_features = [
        packet.posterior_mean, math.sqrt(packet.posterior_variance),
        packet.posterior_mean-packet.prior_mean,
        float(decision.step_index-packet.acquired_step),
        float(kin[0]), float(kin[1]), float(kin[4]), float(kin[5]),
        float(sender_obs["lookahead"]["delta_tau"]),
        float(packet_id in sender_obs["acknowledged_evidence_ids"]),
        float(direction == "carrier_to_scout")]
    need_features = [
        float(need.region), float(need.modality == "traction"),
        need.uncertainty, need.task_relevance,
        need.latest_useful_time-decision.step_index*decision.config.dt,
        need.receiver_progress,
        float(need_age),
        float(packet.region == need.region and
              packet.modality == need.modality)]

    # The receiver's declared task fixes its next physical action independently
    # of the realized SEND outcome. A useful matching innovation replaces the
    # requested duplicate scan; irrelevant needs inspect their requested region;
    # redundant needs require no new scan.
    if context == "useful":
        hold_scan = choice(setup["receiver"], region)
        send_scan = None
    elif context == "irrelevant":
        hold_scan = send_scan = choice(setup["receiver"], requested_region)
    else:
        hold_scan = send_scan = None
    hold = response_branch(decision, packet_id, False, hold_scan, need)
    sent = response_branch(decision, packet_id, True, send_scan, need)
    value = hold["cost"] - sent["cost"]
    return {"seed": seed, "direction": direction, "world": world,
            "context": context, "need_age": need_age,
            "need": asdict(need), "need_delivered": need_delivered,
            "sender_features": sender_features,
            "need_features": need_features,
            "compatible": compatible_need(
                decision.innovation_packets[packet_id], need,
                decision.step_index * decision.config.dt),
            "decision_value": value, "hold": hold, "send": sent,
            "incremental_radio": sent["radio"]-hold["radio"],
            "duplicate_scan_avoided": bool(context == "useful" and
                                            hold["scan_executed"] and
                                            not sent["scan_executed"])}


def _evaluate_job(job):
    return evaluate(*job)


def summarize(rows):
    values = np.asarray([row["decision_value"] for row in rows], dtype=float)
    mean = float(values.mean())
    se = float(values.std(ddof=1) / math.sqrt(len(values)))
    return {"n": len(values), "mean": mean, "standard_error": se,
            "one_sided_95_lower": mean-1.6448536269514722*se,
            "one_sided_95_upper": mean+1.6448536269514722*se,
            "positive_fraction": float(np.mean(values > 0))}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=int, default=990000)
    parser.add_argument("--seeds", type=int, default=4)
    parser.add_argument("--split", required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--need-ages", type=int, nargs="+", default=(0, 8))
    parser.add_argument("--workers", type=int, default=1)
    args = parser.parse_args()
    jobs = [(seed, direction, world, context, age)
            for seed in range(args.start, args.start + args.seeds)
            for direction in DIRECTIONS
            for world in ("safe", "risky")
            for context in ("useful", "irrelevant", "redundant")
            for age in args.need_ages]
    if args.workers == 1:
        rows = [evaluate(*job) for job in jobs]
    else:
        with ProcessPoolExecutor(max_workers=args.workers) as pool:
            rows = list(pool.map(_evaluate_job, jobs, chunksize=1))
    for row in rows:
        print(row["seed"], row["direction"], row["world"], row["context"],
              row.get("need_age"), round(row.get("decision_value", 0.), 5),
              flush=True)
    failures = [row for row in rows if "failure" in row]
    valid = [row for row in rows if "failure" not in row]
    report = {"scope": "NEED admission only; no fitted A4",
              "split": args.split, "start": args.start,
              "seeds": args.seeds, "need_ages": args.need_ages,
              "rows": valid, "failures": failures, "summary": {}}
    for direction in DIRECTIONS:
        for context in ("useful", "irrelevant", "redundant"):
            subset = [row for row in valid if row["direction"] == direction
                      and row["context"] == context]
            report["summary"][f"{direction}:{context}"] = summarize(subset)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2) + "\n")
    print(args.out)
    print(json.dumps(report["summary"], indent=2))


if __name__ == "__main__":
    main()
